### ISSUE TITLE
online listesi

### ISSUE THREAD

**Issue by arda858** [hatoru/suyayazanlar#11]
presence diye bi olay var realtime.co da. onunla halledilir saniyorum

**Comment by kokakirec** [comment]
giriş yapmadan da liste görülebiliyor, bir de bu da canlı güncellense güzel olur. sayfa yenilemeden kendini bile online göremiyorsun.

**Comment by arda858** [comment]
açık dursun. "giriş yapmadan görünme" eklenecek. realtime olayından emin değilim.

**Comment by arda858** [comment]
dışarıya gizlendi. realtime için kolay bi yöntem düşünemedim malesef.
