### ISSUE TITLE
ERROR: Unable to connect to MySQL server!

### ISSUE THREAD

**Issue by hatoru** [hatoru/suyayazanlar#13]
"ERROR: Unable to connect to MySQL server! Error: User a1964402_root already has more than 'max_user_connections' active connections"

Sol frame göçer gibi oldu bir aralık, o sırada bu yazı çıktı ama birkaç saniyeye düzeldi. Öğlen gibi ben de görmüştüm ama sayfayı yenilediğimden ss alamamamıştım. Kitiara-uth-matar arkadaşımızın ricasına binaen atıyor ve bug adıyla tagliyorum Arda eti kemiği senin.

**Comment by arda858** [comment]
google clouda geçildi.
