### ISSUE TITLE
Sol frame vs entry sayısı

### ISSUE THREAD

**Issue by hatoru** [hatoru/suyayazanlar#14]
Son değişikliklerden sonra oldu sanıyorum, başka bir başlığa girilmiş entryler o anda açık olan başlığa yazılmış gibi görünüyor sol frame'de, en azından başlıktaki entry sayısı öyle gösteriyor.

![123](https://cloud.githubusercontent.com/assets/23127986/19848255/546d2250-9f5d-11e6-8927-a2b3cc07feb0.jpg)

Mesela şurada Frank Sobotka başlığındayım, 4 entry var ama solda 7 yazıyor. Yukarıdan yenile'yi tıklıyorum, soldaki tekrar 4'e iniyor ama bir süre sonra diğer başlıklara entry yazıldıkça o sayı yine değişiyor.

**Comment by arda858** [comment]
bu sabit, silinen başlıklarla alakalı bi ayar. bakıcam

**Comment by arda858** [comment]
bu düzeldi.
