### ISSUE TITLE
Ayetleri ve others hesabını kaldıralım

### ISSUE THREAD

**Issue by arda858** [hatoru/suyayazanlar#15]
feyizlendik yeteri kadar. siteyi dış gözlere kapatıcam.

**Comment by hatoru** [comment]
private trackerlardaki gibi sadece login sayfası olsun derim, içeride çok önemli şeyler konuşuluyor sanılsın. misal:

https://what.cd/

nah bunun gibi ağırbaşlı, cool bir dış görünümü olsun. ama login olunca içeride kırıkkaleli faruk gelele desin millete.

**Comment by arda858** [comment]
çabuk kalktı dikkat edersen. yav aklıma geldi o tarz komple kilitli bi sistem ama hem dizaynına üşendim. hem de aktivite de görünsün istedim açıkçası. görsel geliştirme olarak düşünebiliriz ilerde
