### ISSUE TITLE
böyle mi

### ISSUE THREAD

**Issue by kitiara-uth-matar** [hatoru/suyayazanlar#2]
böyle mi

**Comment by hatoru** [comment]
wontfix olarak tagledim mesela karsim bunu siklemiyoruuuuz.swf anlaminda

**Comment by bentakari** [comment]
ben buraya bi sikim yazmam aga ergen ergen hevesler bu ne amk he dilek kutusu he tamam oldu hee hadi bb

**Comment by kitiara-uth-matar** [comment]
neyse bi şe demiyom hevesinizin kırılmaması ve faydalı olabilecek arkadaşları engellememek adına

**Comment by kitiara-uth-matar** [comment]
kimin eksi verdiği görülüyo arda

**Comment by bentakari** [comment]
kendini artılamış ergen yav
