### ISSUE TITLE
Başlık editleyebilme

### ISSUE THREAD

**Issue by hatoru** [hatoru/suyayazanlar#4]
Herkes kendi başlığını düzenleyebilmeli, kendi kendinin doktoru olmalı.

**Comment by arda858** [comment]
bana ownership verebiliyo musun? label ekliyim, yaptigimi checkliyim?

**Comment by hatoru** [comment]
collaborator isteği gelmiş olması lazım.

**Comment by kitiara-uth-matar** [comment]
gereksiz buluyorum yarim saate silinecek zaten

**Comment by arda858** [comment]
silinme yok. ama yine de meh. şöyle bi güzellik var ki, içinde hiç entry olmayan başlıklar yokoluyor. databaseden de uçuyor. yanlış açılanın entryisini silin, yenisini açın geçin.
