### ISSUE TITLE
girişe "hatırla" checkboxu.

### ISSUE THREAD

**Issue by arda858** [hatoru/suyayazanlar#6]
Cookie ile email / şifre vb tarzı bir olayla otomatik login.

**Comment by hecekgl** [comment]
chrome hatirliyor zaten

**Comment by hatoru** [comment]
ornitorenk'te sırf entry numarası verildiğinde sıkıntı olmuyordu ama sitedeki www.ornitorenksozluk.com/entry/123456 şeklindeki linklere tıkladığımızda yeni sekmede login olmamış şekilde geliyordu site.

**Comment by arda858** [comment]
bunu denedim. mobilde çalışmıyor, desktoplar zaten hatırlıyor kendi içinde. şimdilik vazgeçtim.
